language: elixir

elixir:
  - 1.2.3

otp_release:
  - 18.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

before_install:
  - npm install
  - gem install scss_lint

script:
  - mix test
  - mix dogma
  - npm build
  - npm run single-run-test
  - scss-lint .
