language: elixir

elixir:
  - 1.0.4

otp_release:
  - 17.4

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

before_install:
  - npm install

script:
  - mix test
  - grunt test
  - grunt build
