language: elixir

elixir:
  - 1.3.1

otp_release:
  - 19.0

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

before_install:
  - npm install -g yarn
  - yarn install

script:
  - make build
  - mix test
  - mix dogma
