language: erlang

otp_release:
  - 17.4
  - 17.3
  - 17.0

sudo: false

before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.0.3
  - cd ..
  - make -C elixir

before_script: "export PATH=`pwd`/elixir/bin:$PATH"

script: "yes | MIX_ENV=test mix do deps.get, test"

notifications:
  email: false
